# Generated by Django 4.1.5 on 2023-08-07 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sitecategoryapp", "0002_alter_sitecategory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=100)),
                (
                    "category",
                    models.ManyToManyField(to="sitecategoryapp.childcategory"),
                ),
                (
                    "first_discoverer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="place",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
