# Generated by Django 4.1.5 on 2023-08-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecategoryapp", "0002_alter_sitecategory_options"),
        ("placeapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.ManyToManyField(
                related_name="category", to="sitecategoryapp.childcategory"
            ),
        ),
    ]
