# Generated by Django 4.1.5 on 2023-08-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("curationapp", "0001_initial"),
        ("articleapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="curation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curation",
                to="curationapp.curation",
            ),
        ),
    ]
