# Generated by Django 4.1.5 on 2023-08-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("placeapp", "0003_alter_place_category"),
        ("articleapp", "0002_article_curation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="address",
        ),
        migrations.RemoveField(
            model_name="article",
            name="place_name",
        ),
        migrations.AddField(
            model_name="article",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="placeapp.place",
            ),
        ),
    ]
