# Generated by Django 4.2.11 on 2024-03-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_remove_article_address_remove_article_place_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='curation',
        ),
        migrations.RemoveField(
            model_name='article',
            name='place',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='article/'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
