# Generated by Django 4.2.11 on 2024-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_remove_article_curation_remove_article_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='article/'),
        ),
    ]
